<?php
/**
 * Auto-generated test for Boomplay provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class BoomplayTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Boomplay'), 'EmbedPress\Providers\Boomplay class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        // Boomplay is a custom provider that inherits empty hosts from ProviderAdapter
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Boomplay');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertEmpty($hosts, 'Boomplay custom provider has empty hosts (uses regex validation)');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Boomplay('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Boomplay', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.boomplay.com/songs/12345';
        $provider = new \EmbedPress\Providers\Boomplay($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://boomplay.org/test';
        $provider = new \EmbedPress\Providers\Boomplay($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
