<?php
/**
 * Auto-generated test for Canva provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class CanvaTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Canva'), 'EmbedPress\Providers\Canva class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Canva');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Canva should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Canva('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Canva', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.canva.com/design/DAF123/view';
        $provider = new \EmbedPress\Providers\Canva($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://canva.org/test';
        $provider = new \EmbedPress\Providers\Canva($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
