<?php
/**
 * Auto-generated test for Dailymotion provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class DailymotionTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\Dailymotion'), 'Embera\Provider\Dailymotion class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\Dailymotion');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Dailymotion should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\Dailymotion('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\Dailymotion', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.dailymotion.com/video/x5e9eog';
        $provider = new \Embera\Provider\Dailymotion($url);
        $this->assertNotEmpty(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://definitely-not-a-valid-provider.example.com/test';
        $provider = new \Embera\Provider\Dailymotion($url);
        $this->assertEmpty(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
