<?php
/**
 * Auto-generated test for FITE provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class FITETest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\FITE'), 'EmbedPress\Providers\FITE class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\FITE');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'FITE should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\FITE('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\FITE', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.fite.tv/watch/event/abcdef/';
        $provider = new \EmbedPress\Providers\FITE($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://www.trillertv.com/watch/event/abcdef/';
        $provider = new \EmbedPress\Providers\FITE($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://fite.com/test';
        $provider = new \EmbedPress\Providers\FITE($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
