<?php
/**
 * Auto-generated test for Giphy provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GiphyTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Giphy'), 'EmbedPress\Providers\Giphy class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Giphy');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Giphy should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Giphy('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Giphy', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://giphy.com/gifs/funny-cat-abcdef';
        $provider = new \EmbedPress\Providers\Giphy($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://i.giphy.com/media/abcdef/giphy.gif';
        $provider = new \EmbedPress\Providers\Giphy($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://giphy.org/test';
        $provider = new \EmbedPress\Providers\Giphy($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
