<?php
/**
 * Auto-generated test for GitHub provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GitHubTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GitHub'), 'EmbedPress\Providers\GitHub class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GitHub');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'GitHub should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GitHub('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GitHub', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://gist.github.com/user/1234567890';
        $provider = new \EmbedPress\Providers\GitHub($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        // GitHub validateUrl only matches gist.github.com URLs, not github.com/user/repo
        $url = 'https://gist.github.com/abc123';
        $provider = new \EmbedPress\Providers\GitHub($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://gitlab.com/user/repo';
        $provider = new \EmbedPress\Providers\GitHub($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
