<?php
/**
 * Auto-generated test for GoogleDocs provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GoogleDocsTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GoogleDocs'), 'EmbedPress\Providers\GoogleDocs class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GoogleDocs');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'GoogleDocs should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GoogleDocs('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GoogleDocs', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://docs.google.com/document/d/1234567890/edit';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://docs.google.com/presentation/d/abcdef/edit';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_2(): void
    {
        $url = 'https://docs.google.com/spreadsheets/d/abcdef/edit';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_3(): void
    {
        $url = 'https://docs.google.com/forms/d/abcdef/viewform';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_4(): void
    {
        $url = 'https://docs.google.com/drawings/d/abcdef/edit';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://docs.google.com/';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }

    public function test_rejects_invalid_url_1(): void
    {
        $url = 'https://google.com/document/d/123';
        $provider = new \EmbedPress\Providers\GoogleDocs($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
