<?php
/**
 * Auto-generated test for GoogleDrive provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GoogleDriveTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GoogleDrive'), 'EmbedPress\Providers\GoogleDrive class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GoogleDrive');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'GoogleDrive should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GoogleDrive('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GoogleDrive', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://drive.google.com/file/d/1234567890/view';
        $provider = new \EmbedPress\Providers\GoogleDrive($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://drive.google.com/open?id=1234567890';
        $provider = new \EmbedPress\Providers\GoogleDrive($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://docs.google.com/document/d/123';
        $provider = new \EmbedPress\Providers\GoogleDrive($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }

    public function test_rejects_invalid_url_1(): void
    {
        $url = 'https://google.com/drive/file';
        $provider = new \EmbedPress\Providers\GoogleDrive($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
