<?php
/**
 * Auto-generated test for GooglePhotos provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GooglePhotosTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GooglePhotos'), 'EmbedPress\Providers\GooglePhotos class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GooglePhotos');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'GooglePhotos should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GooglePhotos('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GooglePhotos', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://photos.google.com/share/abcdef';
        $provider = new \EmbedPress\Providers\GooglePhotos($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://photos.app.goo.gl/abcdef';
        $provider = new \EmbedPress\Providers\GooglePhotos($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://google.com/photos';
        $provider = new \EmbedPress\Providers\GooglePhotos($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
