<?php
/**
 * Auto-generated test for GoogleCalendar provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GoogleCalendarTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GoogleCalendar'), 'EmbedPress\Providers\GoogleCalendar class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        // GoogleCalendar is a custom provider that inherits empty hosts from ProviderAdapter
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GoogleCalendar');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertEmpty($hosts, 'GoogleCalendar custom provider has empty hosts (uses regex validation)');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GoogleCalendar('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GoogleCalendar', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://calendar.google.com/calendar/embed?src=test@gmail.com';
        $provider = new \EmbedPress\Providers\GoogleCalendar($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://google.com/calendar';
        $provider = new \EmbedPress\Providers\GoogleCalendar($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
