<?php
/**
 * Auto-generated test for GoogleMaps provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GoogleMapsTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\GoogleMaps'), 'EmbedPress\Providers\GoogleMaps class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\GoogleMaps');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'GoogleMaps should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\GoogleMaps('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\GoogleMaps', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.google.com/maps/place/San+Francisco';
        $provider = new \EmbedPress\Providers\GoogleMaps($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://maps.google.com/maps?q=test';
        $provider = new \EmbedPress\Providers\GoogleMaps($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_2(): void
    {
        $url = 'https://goo.gl/maps/abcdef';
        $provider = new \EmbedPress\Providers\GoogleMaps($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://www.google.com/search?q=test';
        $provider = new \EmbedPress\Providers\GoogleMaps($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
