<?php
/**
 * Auto-generated test for Gumroad provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class GumroadTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Gumroad'), 'EmbedPress\Providers\Gumroad class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Gumroad');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Gumroad should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Gumroad('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Gumroad', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://user.gumroad.com/l/product';
        $provider = new \EmbedPress\Providers\Gumroad($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://user.gumroad.com/l/product';
        $provider = new \EmbedPress\Providers\Gumroad($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://gumroad.org/test';
        $provider = new \EmbedPress\Providers\Gumroad($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
