<?php
/**
 * Auto-generated test for Issuu provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class IssuuTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\Issuu'), 'Embera\Provider\Issuu class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\Issuu');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Issuu should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\Issuu('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\Issuu', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://issuu.com/publisher/docs/document-name';
        $provider = new \Embera\Provider\Issuu($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://definitely-not-a-valid-provider.example.com/test';
        $provider = new \Embera\Provider\Issuu($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
