<?php
/**
 * Auto-generated test for LinkedIn provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class LinkedInTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\LinkedIn'), 'EmbedPress\Providers\LinkedIn class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\LinkedIn');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'LinkedIn should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\LinkedIn('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\LinkedIn', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.linkedin.com/in/username';
        $provider = new \EmbedPress\Providers\LinkedIn($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://www.linkedin.com/posts/username-activity-123';
        $provider = new \EmbedPress\Providers\LinkedIn($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://linkedin.org/in/test';
        $provider = new \EmbedPress\Providers\LinkedIn($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
