<?php
/**
 * Auto-generated test for Meetup provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class MeetupTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Meetup'), 'EmbedPress\Providers\Meetup class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Meetup');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Meetup should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Meetup('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Meetup', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.meetup.com/group-name/events/123/';
        $provider = new \EmbedPress\Providers\Meetup($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://meetup.org/test';
        $provider = new \EmbedPress\Providers\Meetup($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
