<?php
/**
 * Auto-generated test for NRKRadio provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class NRKRadioTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\NRKRadio'), 'EmbedPress\Providers\NRKRadio class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\NRKRadio');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'NRKRadio should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\NRKRadio('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\NRKRadio', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://radio.nrk.no/serie/program';
        $provider = new \EmbedPress\Providers\NRKRadio($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://nrk.com/test';
        $provider = new \EmbedPress\Providers\NRKRadio($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
