<?php
/**
 * Auto-generated test for OneDrive provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class OneDriveTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\OneDrive'), 'EmbedPress\Providers\OneDrive class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\OneDrive');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'OneDrive should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\OneDrive('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\OneDrive', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://onedrive.live.com/redir?resid=123';
        $provider = new \EmbedPress\Providers\OneDrive($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://1drv.ms/u/s!AbCdEf';
        $provider = new \EmbedPress\Providers\OneDrive($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://onedrive.com/test';
        $provider = new \EmbedPress\Providers\OneDrive($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
