<?php
/**
 * Auto-generated test for OpenSea provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class OpenSeaTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\OpenSea'), 'EmbedPress\Providers\OpenSea class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\OpenSea');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'OpenSea should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\OpenSea('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\OpenSea', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://opensea.io/assets/ethereum/0x123/1';
        $provider = new \EmbedPress\Providers\OpenSea($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://opensea.io/collection/boredapeyachtclub';
        $provider = new \EmbedPress\Providers\OpenSea($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://opensea.com/test';
        $provider = new \EmbedPress\Providers\OpenSea($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
