<?php
/**
 * Auto-generated test for Podbean provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class PodbeanTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\Podbean'), 'Embera\Provider\Podbean class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\Podbean');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Podbean should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\Podbean('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\Podbean', $provider);
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://definitely-not-a-valid-provider.example.com/test';
        $provider = new \Embera\Provider\Podbean($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
