<?php
/**
 * Auto-generated test for Spotify provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class SpotifyTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\Spotify'), 'Embera\Provider\Spotify class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\Spotify');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Spotify should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\Spotify('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\Spotify', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://open.spotify.com/album/1234567890';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_2(): void
    {
        $url = 'https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_3(): void
    {
        $url = 'https://open.spotify.com/show/1234567890';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_4(): void
    {
        $url = 'https://open.spotify.com/episode/1234567890';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_5(): void
    {
        $url = 'https://open.spotify.com/artist/1234567890';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://spotify.com/track/123';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }

    public function test_rejects_invalid_url_1(): void
    {
        $url = 'https://open.spotify.com/';
        $provider = new \Embera\Provider\Spotify($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
