<?php
/**
 * Auto-generated test for Spreaker provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class SpreakerTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Spreaker'), 'EmbedPress\Providers\Spreaker class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Spreaker');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Spreaker should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Spreaker('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Spreaker', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.spreaker.com/episode/title--12345';
        $provider = new \EmbedPress\Providers\Spreaker($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://spreaker.org/test';
        $provider = new \EmbedPress\Providers\Spreaker($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
