<?php
/**
 * Auto-generated test for TED provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class TEDTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\TED'), 'Embera\Provider\TED class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\TED');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'TED should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\TED('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\TED', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.ted.com/talks/my-talk-title';
        $provider = new \Embera\Provider\TED($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://ted.com/talks/another-talk';
        $provider = new \Embera\Provider\TED($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://definitely-not-a-valid-provider.example.com/test';
        $provider = new \Embera\Provider\TED($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
