<?php
/**
 * Auto-generated test for TikTok provider (embera).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class TikTokTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\Embera\Provider\TikTok'), 'Embera\Provider\TikTok class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\Embera\Provider\TikTok');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'TikTok should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \Embera\Provider\TikTok('https://example.com');
        $this->assertInstanceOf('\Embera\Provider\TikTok', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.tiktok.com/@user/video/1234567890';
        $provider = new \Embera\Provider\TikTok($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://tiktok.org/video/123';
        $provider = new \Embera\Provider\TikTok($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
