<?php
/**
 * Auto-generated test for Twitch provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class TwitchTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Twitch'), 'EmbedPress\Providers\Twitch class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        // Twitch is a custom provider that inherits empty hosts from ProviderAdapter
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Twitch');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertEmpty($hosts, 'Twitch custom provider has empty hosts (uses regex validation)');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Twitch('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Twitch', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.twitch.tv/username';
        $provider = new \EmbedPress\Providers\Twitch($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://clips.twitch.tv/ClipName';
        $provider = new \EmbedPress\Providers\Twitch($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_2(): void
    {
        $url = 'https://www.twitch.tv/videos/123456';
        $provider = new \EmbedPress\Providers\Twitch($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://twitch.com/username';
        $provider = new \EmbedPress\Providers\Twitch($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
