<?php
/**
 * Auto-generated test for Wistia provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class WistiaTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Wistia'), 'EmbedPress\Providers\Wistia class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Wistia');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Wistia should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Wistia('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Wistia', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://fast.wistia.com/medias/abcdef';
        $provider = new \EmbedPress\Providers\Wistia($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://home.wistia.com/medias/abcdef';
        $provider = new \EmbedPress\Providers\Wistia($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://wistia.org/test';
        $provider = new \EmbedPress\Providers\Wistia($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
