<?php
/**
 * Auto-generated test for Youtube provider (custom).
 * Generated by: scripts/generators/generate-provider-tests.php
 *
 * @package EmbedPress\Tests\Unit\Providers
 */

namespace EmbedPress\Tests\Unit\Providers;

use PHPUnit\Framework\TestCase;
use Embera\Url;

class YoutubeTest extends TestCase
{
    public function test_provider_class_exists(): void
    {
        $this->assertTrue(class_exists('\EmbedPress\Providers\Youtube'), 'EmbedPress\Providers\Youtube class should exist');
    }

    public function test_provider_has_hosts(): void
    {
        $reflection = new \ReflectionClass('\EmbedPress\Providers\Youtube');
        $hosts = $reflection->getStaticPropertyValue('hosts');
        $this->assertNotEmpty($hosts, 'Youtube should define hosts');
    }

    public function test_provider_can_be_instantiated(): void
    {
        $provider = new \EmbedPress\Providers\Youtube('https://example.com');
        $this->assertInstanceOf('\EmbedPress\Providers\Youtube', $provider);
    }

    public function test_validates_valid_url_0(): void
    {
        $url = 'https://www.youtube.com/channel/UC1234567890';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_1(): void
    {
        $url = 'https://www.youtube.com/c/MyChannel';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_2(): void
    {
        $url = 'https://www.youtube.com/user/username';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_validates_valid_url_3(): void
    {
        $url = 'https://www.youtube.com/@username';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertTrue(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should accept: {$url}"
        );
    }

    public function test_rejects_invalid_url_0(): void
    {
        $url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }

    public function test_rejects_invalid_url_1(): void
    {
        $url = 'https://notyoutube.com/channel/test';
        $provider = new \EmbedPress\Providers\Youtube($url);
        $this->assertFalse(
            $provider->validateUrl(new \Embera\Url($url)),
            "Provider should reject: {$url}"
        );
    }
}
