/**
 * WordPress dependencies
 */
import { useBlockProps } from '@wordpress/block-editor';

/**
 * Save component for EmbedPress block
 * 
 * This component defines how the block content is saved to the database.
 * For EmbedPress, we use dynamic rendering on the frontend, so this returns null.
 */
const Save = ({ attributes }) => {
    const blockProps = useBlockProps.save();
    
    // EmbedPress uses dynamic rendering on the frontend
    // The actual embed content is generated by PHP
    return (
        <div {...blockProps} data-embedpress-block={JSON.stringify(attributes)}>
            {/* Content will be dynamically rendered by PHP */}
        </div>
    );
};

export default Save;
